version: "3"

server:
  command: "php public/index.php"
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
  address: 0.0.0.0:8080
  pool:
    debug: false
    num_workers: 4
    max_jobs: 1000  # Restart worker after 1000 requests (memory safety)
    supervisor:
      max_worker_memory: 128  # MB, restart if worker exceeds this
  middleware: [ "static", "gzip" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]

# RPC for metrics and worker management
rpc:
  listen: tcp://127.0.0.1:6001

# Prometheus metrics endpoint
metrics:
  address: "0.0.0.0:9180"

logs:
  mode: production
  channels:
    http:
      level: info
    server:
      level: info
      mode: raw
    metrics:
      level: error

# Health check endpoint built into RoadRunner
status:
  address: "0.0.0.0:2114"
